# the original libsvm.jar has svm_predict modified to output result.txt which denotes the scoring of the set
if [ "$1" = 'm' ] || [ "$1" = 'meta' ]
then
	java -jar Lib/meta.jar ${2:-4}
fi
# it seems that the result.txt file generated by libsvm.jar sometimes goes wrong????
# the reason is that libsvm does not remove the original result.txt, it just append to it, so that this will cost the first result to be huge
# this line guarantees that the result.txt can be generated correctly!! since that result.txt is not the standard output file, and is generated by modifying the sources
#rm result.txt
#find . -regex '.*result.\.txt' | xargs rm
for ((i=0; i<10; i++))
do
	java -classpath Lib/ThreeNetworks/jar/*:Lib/ThreeNetworks/bin NNEnsemble data$i.txt test$i.txt result.nn.$i.txt > tmp
done

rm result.tmp.nn.txt
for ((i=0; i<10; i++))
do
	cat result.nn.$i.txt >> result.tmp.nn.txt
done

paste -d ' ' 'result.tmp.nn.txt' 'record.txt' > result.nn.txt
java -jar Lib/auc.jar result.nn.txt list > list.nn.txt

#rm result.txt
echo 'Neural Network Ensemble:'
tail -n 2 list.nn.txt

#./cross.sh
#./single_eva.sh
