# the original libsvm.jar has svm_predict modified to output result.txt which denotes the scoring of the set
if [ "$1" = 'm' ] || [ "$1" = 'meta' ]
then
	java -jar Lib/meta.jar ${2:-4}
fi
# it seems that the result.txt file generated by libsvm.jar sometimes goes wrong????
# the reason is that libsvm does not remove the original result.txt, it just append to it, so that this will cost the first result to be huge
# this line guarantees that the result.txt can be generated correctly!! since that result.txt is not the standard output file, and is generated by modifying the sources
rm result.txt
#find . -regex '.*result.\.txt' | xargs rm
for ((i=0; i<10; i++))
do
	java -classpath Lib/libsvm.jar svm_train data$i.txt > tmp
	# why can't I generate result$i.txt files??
	# seems that the output file does not have influence
	# have put o.txt more arguements here!!!!
	java -classpath Lib/libsvm.jar svm_predict "test$i.txt" data$i.txt.model o.txt > tmp
	rm data$i.txt.model
	#rm data$i.txt
	#rm "test$i.txt"
	rm o.txt

	mv result.txt result$i.txt
done

java -jar Lib/ResultsList.jar

for ((i=0; i<10; i++))
do
   rm result$i.txt
done

java -jar Lib/auc.jar result.txt list > list.txt

echo 'SVM Ensemble:'
tail -n 2 list.txt
#./single_eva.sh
